apiVersion: v1
kind: Secret
metadata:
    name: web-frontend-secret
type: Opaque
stringData:
    COOKIE_SECRET: ENC[AES256_GCM,data:9woj0lEyOjEuOHn9iUcxQotHhkz3Lig/5atM4IiB1glSzWzqRHCtNt7N,iv:t8rCBp28eSGzIhPgMgJV10ZcZlgI1oXAmv8HiyhRu4Q=,tag:DniJ9L5gVtYeIj8YJUpWjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeHMvRmpiSlFnVUk5WDBX
            SlpHSUI1Wld4bVBUNUhwNzhzK3hXaWNuRjBNClZJbkF4dEEvTllYRUsweDNHSXB2
            WTlrTUdTdWN5Zko5bUxZZzFQVU9ENGcKLS0tIGdxVFpzejhCYWZPTHpIMFI3clNY
            eW0rSXFtSmYybEhYNElUTXVSeUpHVlkKBlAKOlAe5C9br0giH6HlCfXJBKsxCP2n
            294iNzo7isX6t4fDuq52hGSmqCj/fts1YCWuOHGB9vLtR6DGSIx/+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age192pk2xs5v4dan3rl2hf4ex59m8v7wurj05gzvxpypwwlzc09kegsrc7cf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T12:44:04Z"
    mac: ENC[AES256_GCM,data:2Mfp0mS+ITA3GJpJjpA9P7zkuhq7mDzFY2i2vPP4q62ziEIGRhoRmrf/bTYmQDhSNgTtGuKOeYxVwjzup0TRpn8UQjmc5YBoeoV/+KJCUiR29Blig+MrEX5hBEOcS3ChK0r+azxUt3+pZ3lQ5h97ThyLB70aSLBhpxg7+uXSWVU=,iv:E3Hb2osiCtgyPN28LoPvhtSv/x0C31uRlyJqle2VtgU=,tag:2jiY5kMdSyhSIOlOD27loQ==,type:str]
    version: 3.13.3
