apiVersion: v1
kind: Secret
metadata:
    name: api-gateway-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:9Adm3tUHQZZFxW6oOOoKapsj69SPKqLSKVl54B5iYjioVVo1NM0rtneqe3qNZuLQGwKpQt32Q1EpQEK90EoIulKekTcspu4KRB/+bgpXUd7Tzg==,iv:vh1C2pyGu4ljPc9Ez2gQZcBWOKn6cYdeetTTtSHgjWo=,tag:e9MPHwKPpKghHY9bCB1w5w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Xr5s9RIdxuqsuFE0lqJFXC7WIYkViT41FXN5NVIM2/HV5RoooijThsTB49UC,iv:luNIZCfeki+a+h/WLbUBPh/TV/ywSL2iee8GIo/wjhI=,tag:0Pwbw9XfzcINGAxHufxxCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVHBvNDBuS2FuU3lUY3Jl
            d0hsUDJKZXFjcEU1U09Od013dnlWREZONnpzCjkxVUlld01PclNoZXgvVkRESWtR
            WlpHSlpxVlREcWRZWmxDcm13VE1VQmsKLS0tIElsRnN1S0dkTFU5ckFaM2U2MTk1
            RnRCNkZtT2NKZmpWWVBCL0xhM21JK0kKz/udvRD/6b+E5UNUKf+iBDnYJD5wB02C
            VvGz//SR/UD3rT12VXCygP2HOAv/FqL/lCgbdVfZIhULxNa5pkeIUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age192pk2xs5v4dan3rl2hf4ex59m8v7wurj05gzvxpypwwlzc09kegsrc7cf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T12:44:04Z"
    mac: ENC[AES256_GCM,data:+Pjt583dDexxOnFA5Phv4/1q4wUyXz6GmN57abvdqwTrcnNtX1yxZS+5WUGp8vx3uYfjwCOquZUQYD04uLpTEKojmGkN/RM3yceN1TPwxAsaEa54xzwW+hMCexp3olfGy+ElnV2va9XaDjj4S2w9Gz2QuQLdQSy/zeGBnj2h+tw=,iv:kfdB9wPlY36HuFRzlbIC2lEKKFDCyOiSZSAT3TbLWb4=,tag:XhzRJ7q0DOGCsFUTPztKTA==,type:str]
    version: 3.13.3
