apiVersion: v1
kind: Secret
metadata:
    name: api-gateway-secret
    namespace: manveersyan-group
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:B3YmyM+NJVTNb6+Dhl0FFIlyGhkKj7Auy4Pfdf9yzJ2o3YzRHC8t/osSkSVYcDLUQCUuA7dSjAocOeai5Ebj1Brl+EKu0Tq8p/uBfCBYe6mtINXPVHjQAMSoDMj0eSP1LiTJ/FJZGPz/m/43F2uU9ai55wTD3c4vUNv4TEFvBv8=,iv:SSxiM0sAjExvmBnrOZg6F/n2MtYlDNIvkGwnFSwK9qY=,tag:Od7YaoQ+EO3Qw7VlSuiqfg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:4nBr31jW5JGDycWf0d8pZC2mCPltCqVR1X/XhspFPZJF8RHI3Hc=,iv:xtVQSYeCohboNU/iiPX5t9Z1XSapy+wKuV7/3QccURk=,tag:OMHX1k2ItUrGMlNVkPWClA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcGxCNGpsQ3c3enJBMTFQ
            UGRHSFVXM1MwQnRQaXZpZnF6K1Vxb2xwT1hnCjl4WGE4TTNwTDdxUlI4bWs3ZWRw
            TEk0R1VORlF5M2JJWEdGelhURzk2UHcKLS0tIGFZVEl0alhjQmUrWUpMWkJSVXY0
            ZU5lQllqZVEraVJKc3Q1bTZiQlFEaUUKdV+6q7+acf9eQndtpSm8/qEXjmmgrJWT
            XcLa/MwMRC6xCESLMLUg1KQh8H/BFuzcrwZn/cBB37gsFT7FX73JYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age192pk2xs5v4dan3rl2hf4ex59m8v7wurj05gzvxpypwwlzc09kegsrc7cf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T13:11:57Z"
    mac: ENC[AES256_GCM,data:rSYFDfxWt1eSLJ0vb9m0TJbQ38ulb3Q7P1Qsd940PBlyOTLFH8ZqzQHhiMmgIYFD01mXykooWYtTuDFbvnwJW7CKhF/z8p7OAxeOBrzt2g6VUuTxx8kgkHw4q30Qnztr808SX5zYmGKF3ZJPu68aRi2bPnhNRnJFQnWuBiJxc6k=,iv:Zd0Il5quKjdDzmH6eH9CuSFCcg5VrenTLKI5Z4Tv2qE=,tag:9KalTe6S0+CaOnPy9kvQYA==,type:str]
    version: 3.13.3
