apiVersion: v1
kind: Secret
metadata:
  name: web-frontend-secret
  namespace: manveersyan-group
type: Opaque
stringData:
  API_GATEWAY_URL: "http://api-gateway:8080"
  AUTH_SERVICE_URL: "http://auth-service:5000"
