apiVersion: v1
kind: Secret
metadata:
    name: web-frontend-secret
    namespace: manveersyan-group
type: Opaque
stringData:
    API_GATEWAY_URL: ENC[AES256_GCM,data:qwNaP8xLJiq61QPBVrEQnolxmjYpfzs=,iv:65qnVUgJAqtZWufGzR0ZLZ9vbsdmmIqEHlTRpElAzpg=,tag:mYtY4mX5HGEMOxd1M5uO7A==,type:str]
    AUTH_SERVICE_URL: ENC[AES256_GCM,data:QqZPqdtM9/xZBqi5qXGbC7Wvekxc0AMy,iv:54cTq+Eb4O46AYR9MlSnxltRCjcaypPaw/5To/B8g7A=,tag:DlkxgikPb1DCzfHRzPMy7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZczFYNitGZjRTZE5XQlpU
            cXVrUi9GazRQRlcyUC94K0M2NERqbUc1andZCmxhbDZ5MEYwSHMyczdSbjJIblpG
            RzRkWVJ3WTV3VTBIdUNtUEZ1SWFCcWcKLS0tIGhkTW91eU9FaXBaUm9scVVtNmcr
            bkRndUZQZVMvUHB0THJBWVpsMEhJRGsKiYWb0p5mVG0kBzoQUiq7UMeN0VNFgi6f
            ScgaMqsGXWpSz44A+Aa0fOB7d5L7gV+irRub3+f9PXlxweRwDmvRhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age192pk2xs5v4dan3rl2hf4ex59m8v7wurj05gzvxpypwwlzc09kegsrc7cf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T13:11:57Z"
    mac: ENC[AES256_GCM,data:UuSsO7Re39MnermWSf+XLT+x2ynaWB5olV3K3cYleyoC+AC18+SAIez+mZ2FtiZa6RE3NkEIcJ3kJdAA5bROBWIHikRo+y5u7T1Uy78lYZYfmezMZmyafmZmmMUObYQzQflWN5U6x0PhAtR0BStyZxhsv5bAccc5UFUkYYuol8I=,iv:GqGTy3GQCdkeSWU1Dax/0axkFFgTiFfKP51KjoxU4hM=,tag:3E0UCI9I5LV7BdXWZuoBHA==,type:str]
    version: 3.13.3
