apiVersion: v1
kind: Secret
metadata:
    name: notification-service-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:gYLbkC7U9I4MiWPr+udLdPAujd17xuqnFi2nx4CH7TG3kJ+IoNuMwkkOSNVa7d4FnUnwRmHoWTLh1iZdXPmw8+FKgGnpIHqTT/2gevx4URLXmw==,iv:p+b5cD2a2T501BEDheN4TlmzK4ikGVAAhhmJ4PFJCj8=,tag:3d6I/pPiCK32GpYPlUuDXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMR2g0dnV1RXpJa0tTYTV4
            WmdzWEJoMm5MR24xQnZsSWNEMTM2b0k5VFRJCjhkcDBZdVlXTjdDMTJ3OU9jcnBH
            T040VzhxV3ZTZjFPNWVBN0wvdjhQZFEKLS0tIHNlYWNPUncvZDV6bzFtdnZXUnVq
            OFA0NFMxM0dxSTY1Y0IxUmh4aVdMVGMKTdzBGNBiqY1q/1DFBaZClsLC0by6hvpo
            mCRwI8B0O6CmHgDip9zrFsRjxQ+l4tnw7+AinUiAwoAqDywD1qr3vA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age192pk2xs5v4dan3rl2hf4ex59m8v7wurj05gzvxpypwwlzc09kegsrc7cf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T12:44:05Z"
    mac: ENC[AES256_GCM,data:mx47ubKizx9crBj+bSGXr391uw5qc578kc6kFoadzzsIQ9smq1X2Unvr+WfeR4TYVnkBdIBxQ1VJe/t98dDLMnwYF2WM4PrZIS79PK0SnNiJbR4PKuyYZxcoy5W0N5fRBhXc8I21Fcfk+JbkdFgUoVUQe8Or+pbCn7+1B5nGJO8=,iv:Y6J5L/MpL/EmMSH8kMj9+AUXa3AaTHATcCZk+FTuz7E=,tag:aWLpxp8jSkEIK2XYUXZTiQ==,type:str]
    version: 3.13.3
