apiVersion: v1
kind: Secret
metadata:
    name: notification-service-secret
    namespace: manveersyan-group
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:WaP3JPejNfQTt9VUPIGhqycUyEmo1oeTF6hEeWF3ldpfpOkirgnopJE5rOALCchPh7TiEU1GKK41bU/UQNwvLiMa6LuqZa4lYGxyuXBFONIMzJhb+O3dW7w9VihTQMKIxC7q4trUSJMsm03+5d0dCkgk0mJn4rkC6ys9VMwE4mg=,iv:FYquPIC7ek+6Im17L4VsAUUXLPCzsdi7jWS0Eb9ZY74=,tag:Pi8+RFfw5PhGo8nWSjPz5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRmh1elFpWWlxdktoMU12
            VzF2a1k0cThwNTJTS3UyTTZCc3R3WnlkeURRClRsK2pOQUlNeVptRXNVZDJQODNS
            Z3NYL0VFOGVhSWdJdms3UEEzN2RRSmsKLS0tICsrT0hxMThnYXJqRDhTbFFhcDF1
            b1YxcXVWaVNsQVh6dWNsQ25MdlZCY3MKQgnAtVtuj4e8py2XGNubJJg/CinTRAtI
            v+hI2Ezvpgt9ozSnu6E5F6+N9k/uku+zfQBymwGldLVzHEgmV7n7+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age192pk2xs5v4dan3rl2hf4ex59m8v7wurj05gzvxpypwwlzc09kegsrc7cf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T13:11:57Z"
    mac: ENC[AES256_GCM,data:b4sMSR228urBzkBLwwjQb66u0Rjh+OHz8mqmbl+vdmRU8yGf9puhv4HeUW7eeJtuPwh9qHr6Oj3VC3jUF8gENPL5bywiwxC6au6rk8I/blQ8qoUH+CXYdeIKkKi2FZMhF5ulNruboHPPVKuAnBfPxVX/viodOr86Qf+pmRkwWbU=,iv:6XlVe+IOxlbnHvzqxFYC+ebP5n9HggfoNzUuJx1sEJA=,tag:s32VxND/V2Urf/dIdjX7mA==,type:str]
    version: 3.13.3
