export const initialTasks = [
  {
    id: "task-101",
    title: "Implement Authentication Flow & JWT Handling",
    description: "Build secure token-based user authentication, token refresh logic, and role-based route protection.",
    category: "Development",
    priority: "High",
    status: "In Progress",
    lead: "Manveer Singh",
    dueDate: "2026-09-10",
    estimatedHours: 16,
    tags: ["Security", "Backend", "API"],
    archived: false,
    createdAt: "2026-08-25T10:00:00.000Z"
  },
  {
    id: "task-102",
    title: "Design UI Glassmorphism Theme System",
    description: "Create design tokens, CSS variables, and glassmorphic card elements for dark/light dashboard themes.",
    category: "Design",
    priority: "Urgent",
    status: "Completed",
    lead: "Sarah Connor",
    dueDate: "2026-08-30",
    estimatedHours: 12,
    tags: ["UI/UX", "CSS", "Frontend"],
    archived: false,
    createdAt: "2026-08-20T14:30:00.000Z"
  },
  {
    id: "task-103",
    title: "Q4 Marketing Strategy & Campaign Launch",
    description: "Draft content calendar, coordinate social media collateral, and schedule promotional email sequences.",
    category: "Marketing",
    priority: "Medium",
    status: "To Do",
    lead: "Alex Rivera",
    dueDate: "2026-09-15",
    estimatedHours: 20,
    tags: ["Growth", "Campaign", "Content"],
    archived: false,
    createdAt: "2026-08-28T09:15:00.000Z"
  },
  {
    id: "task-104",
    title: "Quarterly Financial Audit & Budget Allocation",
    description: "Review operational expenditure, calculate ROI on dev tooling, and finalize next quarter budget allocations.",
    category: "Finance",
    priority: "High",
    status: "Under Review",
    lead: "Elena Rostova",
    dueDate: "2026-09-05",
    estimatedHours: 10,
    tags: ["Audit", "Budget", "Finance"],
    archived: false,
    createdAt: "2026-08-22T11:00:00.000Z"
  },
  {
    id: "task-105",
    title: "Database Schema Migration & Indexing",
    description: "Optimize query execution plan, add composite indexes on high-frequency tables, and execute zero-downtime migration.",
    category: "Development",
    priority: "Urgent",
    status: "Backlog",
    lead: "Manveer Singh",
    dueDate: "2026-09-20",
    estimatedHours: 24,
    tags: ["Database", "SQL", "Performance"],
    archived: false,
    createdAt: "2026-08-29T16:00:00.000Z"
  },
  {
    id: "task-106",
    title: "CI/CD Deployment Pipeline Automation",
    description: "Set up GitHub Actions / GitLab CI workflows with automated unit tests, build validation, and staging deployment.",
    category: "Operations",
    priority: "Medium",
    status: "In Progress",
    lead: "Devon Vance",
    dueDate: "2026-09-12",
    estimatedHours: 14,
    tags: ["DevOps", "CI/CD", "Automation"],
    archived: false,
    createdAt: "2026-08-26T08:45:00.000Z"
  },
  {
    id: "task-107",
    title: "Customer Onboarding Experience Redesign",
    description: "Streamline user registration steps and introduce interactive product walkthrough guide.",
    category: "Design",
    priority: "Low",
    status: "To Do",
    lead: "Sarah Connor",
    dueDate: "2026-09-25",
    estimatedHours: 18,
    tags: ["UX", "Product", "Onboarding"],
    archived: false,
    createdAt: "2026-08-31T13:20:00.000Z"
  },
  {
    id: "task-108",
    title: "API Performance & Response Caching",
    description: "Integrate Redis caching layer for heavy read endpoints to reduce server response latency below 50ms.",
    category: "Development",
    priority: "High",
    status: "Completed",
    lead: "Manveer Singh",
    dueDate: "2026-08-29",
    estimatedHours: 8,
    tags: ["Backend", "Redis", "Optimization"],
    archived: false,
    createdAt: "2026-08-15T09:00:00.000Z"
  }
];
