apiVersion: v1
kind: Secret
metadata:
    name: auth-service-secret
    namespace: manveersyan-group
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:CoA14RmfL1ryDpiAS/oExUsJZwCS8+sG7KMdNDYPO5wstTqSJ9i7V2hcxgEU8eyWE1qv6HndKajWcfLw/glUgfZGHHmwP2X748IAhNPry6QxoMWdG5dQ94G4Fv7E9o4GZVEamVom8oBI7ZwT8JpQfTtYMgFwWWHpmNwRqeY6iJk=,iv:siuPbpkNq2eluvwWRoeHinxpB22i28m1sLLh5Pwvk7g=,tag:dL1FHt7Q+SVIkHe2TQgHKA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:UYDFVm6KzOR+VELENGXyhWYGwZVx6OR3nTdUi/9CdsUH0XxgVD8=,iv:/6+JoQC75ENlNHpEv9DOXEAtb70V879Iy6NrtlSKMIs=,tag:RNfWqC9fu+7jW+BUT8DbJQ==,type:str]
    SMTP_USER: ""
    SMTP_PASS: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaW04VGdpZHpBMWd3S3Yw
            OGo4Um5LNS96OHVvMzRqUm9wNVA0RURIUTFRCmtLUUorNGNJRzVneDRVN3ZiVWxQ
            YWhhRmZvdXVLRWh5REJoVjViOHdOVTgKLS0tIGtUMTJiMkZYdmRZY3lpbEE4MEQx
            dHlvQWNvTFhoTlIveU9tc0VFWnhvRkEKvkdHNt08K7anP3FfnpHpTJtmPtY3YBzV
            0DhYfXygeiaL66cew3TUzjgx7rKn0VI+0vvSgjKcHeMAIZJQjvlerQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age192pk2xs5v4dan3rl2hf4ex59m8v7wurj05gzvxpypwwlzc09kegsrc7cf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-09T13:11:57Z"
    mac: ENC[AES256_GCM,data:e0vFHURdvuOXkoOdkEFOSwj1kis1tn7JGrzx6f3fEX1iUaEpNx7jaFlVrD9GHlLOWhJ2VTptzwDxSD50E/qG2Fg0RKeybxoKbt52szHPYSzLfIaxfNP5AeL7N1Cnu9PsAw6wPgW2t0PuYkj5isDdUCAbcxYN0M2qb92dN8z9l+w=,iv:RXIl85ARvIggIcPN66LlNJo8mjUHxK7pgyPO+8OIyW8=,tag:kQYZt94DNGZSLjGcBzLewg==,type:str]
    version: 3.13.3
