apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: manveersyan-group
type: Opaque
stringData:
  DATABASE_URL: "postgres://produser:ProdStrongPassword987!@manveersyan-prod-db.c123456789.us-east-1.rds.amazonaws.com:5432/appdb?sslmode=disable"
  JWT_SECRET: "super-secret-jwt-token-key-32bytes-min"
  SMTP_USER: ""
  SMTP_PASS: ""
