apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manveersyan-group

resources:
  - ../../base
  - apps/web-frontend/secret.enc.yaml
  - apps/api-gateway/secret.enc.yaml
  - apps/auth-service/secret.enc.yaml
  - apps/notification-service/secret.enc.yaml

components:
  - ../../components/strict-network

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: web-frontend-config
    envs:
      - apps/web-frontend/params.env
  - name: api-gateway-config
    envs:
      - apps/api-gateway/params.env
  - name: auth-service-config
    envs:
      - apps/auth-service/params.env
  - name: notification-service-config
    envs:
      - apps/notification-service/params.env

images:
  - name: registry.gitlab.com/manveersyan-group/web-frontend
    newTag: v1.0.0
  - name: registry.gitlab.com/manveersyan-group/api-gateway
    newTag: v1.0.0
  - name: registry.gitlab.com/manveersyan-group/auth-service
    newTag: v1.0.0
  - name: registry.gitlab.com/manveersyan-group/notification-service
    newTag: v1.0.0

patches:
  - target:
      kind: Deployment
      name: web-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: auth-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Deployment
      name: notification-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
