apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manveersyan-group

resources:
  - ../../base
  - pdb.yaml
  - network-policy.yaml

patches:
  - target:
      kind: Deployment
      name: web-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: auth-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
