apiVersion: v1
kind: Secret
metadata:
    name: auth-service-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:lesUhm1oYq6EmKUKZi+hE8odYD0cC84X/Nns2LlSNzrCZKiRR7IRaG8EuIvoLjrpjhTczCpmDvOvFPRzY83ennrai1y2/ymcE7QGNL/ecnYoRw==,iv:olv8TLvXtGR321IOsFvEC09CreMEy0UPV5jBYhjqVEU=,tag:W4CEOyTaABK/g8aFbZWe/w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:FRFbom4PnUvDI6f+bRw03L3sO2nJylFh/zNwyU72ADo8B3qEwy3bCBrPo1M+,iv:JRrghp9ZQzhfKURAKfqW+XtFwiU7ZsmQalFIDecHTJU=,tag:3XpNwKsLPVkdO9/SepPgZw==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:SEiyITA7U59nCnD9,iv:y2AakDt/RqQV4Z3qjou4Hb0xYlJbNoH+1v3gOYpLFXo=,tag:wuQY85vhzAvT6smbzVetaQ==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:xT09btcAJkfdtfc0,iv:VPqTSoXbkq0BVVVGgE9L3rWv6rGLUskRw7xTIfQpMsk=,tag:rQuj9XDae+l2+BGthTRmOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5d2lIT3ZoWkN4emVnV1cv
            Q0dYUW5EenAvUUNFNGcySit2bHhranhmRFR3CmtId2Y2Z1d4eWNUNG51VDI0b29s
            Z01NM2xxcUxLMGRiUUdOdS9vNjNyRlUKLS0tIGdPZXNzMG0yZkdxQ3U4SWVxN0Nm
            M2QzYkpRNnhlaHVHTndUYVJiNmR1WTQKw41K0P3WTaiPffcBqZlh8zXLj9WjrlfS
            MWEYjw9Ll6fXL9fkl3AZX6nuKFqItiGI6UvTdeUZ7RLnHYfxa/Y61g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age192pk2xs5v4dan3rl2hf4ex59m8v7wurj05gzvxpypwwlzc09kegsrc7cf7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T12:44:05Z"
    mac: ENC[AES256_GCM,data:/NDMqWLjQfVV/gWF9ISaUkoCq0Pk1cLFSgOIJfdqsauA3ffsGgDccDjx9qTa0hOvWklb4aY3eHm1g+wBXtFwALv8USsZzaARcFpu5GLC5sUAzCY12IjRzKzbCxGlmmmXBz07psY91i9IZ+nRX5VbaYUd4QbNp815fvoy69IoSLY=,iv:YVIMmrr7Zz0aB94AiPoGDbsRg8uzeugjqqKMOeuz/UM=,tag:Ewg5+htqUJ5ieWfNQvS+fg==,type:str]
    version: 3.13.3
