# ==============================================================================
# Namespace Definition
# Path: k8s/base/namespace.yaml
# ==============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: manveersyan-group
  labels:
    app.kubernetes.io/part-of: manveersyan-platform
    environment: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
