apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secret
  namespace: manveersyan-group
type: Opaque
stringData:
  DATABASE_USER: produser
  DATABASE_PASSWORD: ProdStrongPassword987!
  DATABASE_URL: postgres://produser:ProdStrongPassword987!@manveersyan-prod-db.c0fcqy40cv6i.us-east-1.rds.amazonaws.com:5432/appdb?sslmode=require
  JWT_SECRET: SuperSecretProductionJwtSigningKey2026!
