# ==============================================================================
# Microservice Workload Service Accounts (Least Privilege / No API Access)
# Path: k8s/base/serviceaccounts.yaml
# ==============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-frontend-sa
  namespace: manveersyan-group
  labels:
    app.kubernetes.io/name: web-frontend
    app.kubernetes.io/part-of: manveersyan-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: manveersyan-group
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: manveersyan-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: manveersyan-group
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: manveersyan-platform
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: manveersyan-group
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: manveersyan-platform
automountServiceAccountToken: false
