project_name       = "manveersyan"
environment        = "prod"
region             = "us-east-1"
vpc_cidr           = "10.0.0.0/16"
azs                = ["us-east-1a", "us-east-1b"]
public_subnets     = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets    = ["10.0.10.0/24", "10.0.11.0/24"]
allowed_ssh_cidr   = "0.0.0.0/0" # Restricted in Security Hardening Playbook
ec2_instance_type  = "t3.small"
rds_instance_class = "db.t3.micro" # Keep micro for cost <$200/mo constraint; can scale to db.t3.medium
rds_username       = "produser"
rds_password       = "ProdStrongPassword987!"
enable_monitoring  = true
